name: Deploy
on:
  push:
    branches:
      - main
env:
  TZ: Asia/Shanghai

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.4
        with:
          persist-credentials: false
          fetch-depth: 0

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "16.x"
          registry-url: "https://registry.npmjs.org"
          cache: "pnpm"

      - name: Install deps
        run: pnpm install

      - name: Build
        run: |
          pnpm build:vite

      - name: Deploy 🚀
        uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          publish_dir: dist
          commit_message: ${{ github.event.head_commit.message }}
          # keep_files: false
          force_orphan: true

      # - name: Deploy to Server 📂
      #   uses: SamKirkland/FTP-Deploy-Action@4.2.0
      #   with:
      #     server: ${{ secrets.FTP_SERVER }}
      #     username: ${{ secrets.FTP_USERNAME }}
      #     password: ${{ secrets.FTP_PASSWORD }}
      #     local-dir: ./dist/

  # deploy-server:
  #     needs: build-and-deploy
  #     runs-on: ubuntu-latest
  #     steps:
  # - name: Prepare SSH to work with the remote server
  #   run: |
  #     cd ~ && mkdir .ssh &&
  #     touch ~/.ssh/known_hosts &&
  #     echo "${{ secrets.SSH_HOSTKEY }}" > ~/.ssh/known_hosts

  # - name: Deploy to Server
  #   uses: easingthemes/ssh-deploy@main
  #   env:
  #       SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
  #       ARGS: "-rltgoDzvO --delete"
  #       SOURCE: "dist/"
  #       REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
  #       REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
  #       REMOTE_USER: ${{ secrets.REMOTE_USER }}
  #       TARGET: ${{ secrets.REMOTE_TARGET }}
  #       EXCLUDE: "/dist/, /node_modules/, ./.user.ini"
